/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: isnainul (https://sketchfab.com/isnainul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/book-shelf-48355d20f0f14234afc2fa3f263b995c
Title: Book Shelf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model(props) {
  const { nodes, materials } = useGLTF('/assets/models/book_shelf/scene1.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rak_Buku_Handle_Rak_Buku_Handle_0.geometry}
        material={materials.Rak_Buku_Handle}
        position={[90, 200, 40]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rak_Buku_Atas_Rak_Buku_Atas_0.geometry}
        material={materials.Rak_Buku_Atas}
        position={[90, 200, 40]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rak_Buku_Bawah_Rak_Buku_Bawah_0.geometry}
        material={materials.Rak_Buku_Bawah}
        position={[90, 200, 40]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={100}
      />
    </group>
  )
}

export default Model;

useGLTF.preload('/assets/models/book_shelf/scene1.gltf')
